- pkg:composer/nigelheap/roles@0.9
- pkg:composer/nigelheap/roles@1.1
- pkg:composer/nigelheap/roles@1.2.0
- pkg:composer/nigelheap/roles@1.2.1
- pkg:composer/nigelheap/roles@1.2.2
- pkg:composer/nigelheap/roles@1.2.3
- pkg:composer/nigelheap/roles@1.2.4
- pkg:composer/nigelheap/roles@1.3.0
- pkg:composer/nigelheap/roles@1.4.0
- pkg:composer/nigelheap/roles@1.4.1
- pkg:composer/nigelheap/roles@1.5.0
- pkg:composer/nigelheap/roles@1.5.1
- pkg:composer/nigelheap/roles@1.5.2
- pkg:composer/nigelheap/roles@1.5.3
- pkg:composer/nigelheap/roles@1.5.4
- pkg:composer/nigelheap/roles@1.6.0
- pkg:composer/nigelheap/roles@1.7.0
- pkg:composer/nigelheap/roles@1.7.1
- pkg:composer/nigelheap/roles@2.0.0
- pkg:composer/nigelheap/roles@2.0.1
- pkg:composer/nigelheap/roles@2.0.2
- pkg:composer/nigelheap/roles@2.1.0
- pkg:composer/nigelheap/roles@2.1.1
- pkg:composer/nigelheap/roles@2.1.2
- pkg:composer/nigelheap/roles@2.1.3
- pkg:composer/nigelheap/roles@2.1.4
- pkg:composer/nigelheap/roles@2.1.5
- pkg:composer/nigelheap/roles@2.1.6
- pkg:composer/nigelheap/roles@2.1.7
- pkg:composer/nigelheap/roles@3.0.1
- pkg:composer/nigelheap/roles@3.0.2
- pkg:composer/nigelheap/roles@3.0.3
- pkg:composer/nigelheap/roles@3.0.4
- pkg:composer/nigelheap/roles@3.0.5
- pkg:composer/nigelheap/roles@5.3.1
- pkg:composer/nigelheap/roles@5.3.2
- pkg:composer/nigelheap/roles@5.3.3
- pkg:composer/nigelheap/roles@5.3.4
- pkg:composer/nigelheap/roles@5.3.5
- pkg:composer/nigelheap/roles@5.4.1
- pkg:composer/nigelheap/roles@5.4.2
- pkg:composer/nigelheap/roles@5.4.3
- pkg:composer/nigelheap/roles@5.4.4
- pkg:composer/nigelheap/roles@5.4.5
- pkg:composer/nigelheap/roles@6.0.0
- pkg:composer/nigelheap/roles@v1.0.0
- pkg:composer/nigelheap/roles@v1.0.1
- pkg:composer/nigelheap/roles@v1.0.2
- pkg:composer/nigelheap/roles@v1.0.3
