- pkg:composer/wp-cli-configmaps/wp-cli-configmaps@1.0.0
- pkg:composer/wp-cli-configmaps/wp-cli-configmaps@1.0.1
- pkg:composer/wp-cli-configmaps/wp-cli-configmaps@1.0.2
- pkg:composer/wp-cli-configmaps/wp-cli-configmaps@1.0.3
- pkg:composer/wp-cli-configmaps/wp-cli-configmaps@1.0.4
