- pkg:composer/minimal/config@v0.1.0
- pkg:composer/minimal/config@v0.1.1
- pkg:composer/minimal/config@v0.1.2
- pkg:composer/minimal/config@v0.1.3
- pkg:composer/minimal/config@v0.1.4
- pkg:composer/minimal/config@v0.1.5
- pkg:composer/minimal/config@v0.2.0
