- pkg:composer/promphp/prometheus_push_gateway_php@v1.0.0
- pkg:composer/promphp/prometheus_push_gateway_php@v1.0.1
- pkg:composer/promphp/prometheus_push_gateway_php@v1.1.0
- pkg:composer/promphp/prometheus_push_gateway_php@v1.1.1
