- pkg:composer/bpartner/tasks@1.0
- pkg:composer/bpartner/tasks@1.1
- pkg:composer/bpartner/tasks@1.1.1
- pkg:composer/bpartner/tasks@2.0
- pkg:composer/bpartner/tasks@2.1
- pkg:composer/bpartner/tasks@2.2
- pkg:composer/bpartner/tasks@2.2.1
- pkg:composer/bpartner/tasks@2.3
- pkg:composer/bpartner/tasks@2.3.1
- pkg:composer/bpartner/tasks@2.3.2
