- pkg:composer/jamesgober/config@v1.0.0
- pkg:composer/jamesgober/config@v1.0.0-RC.2
- pkg:composer/jamesgober/config@v1.0.0-RC.4
- pkg:composer/jamesgober/config@v1.0.0-RC.5
- pkg:composer/jamesgober/config@v1.0.0-RC3
- pkg:composer/jamesgober/config@v1.0.0-Rc.1
